TRANSLATION_TRACKING_ENABLED = True
ROTATION_TRACKING_ENABLED = True

NUMBER_OF_NETWORK_OUTPUTS = 0

if TRANSLATION_TRACKING_ENABLED : 
    NUMBER_OF_NETWORK_OUTPUTS += 3

if ROTATION_TRACKING_ENABLED :
    NUMBER_OF_NETWORK_OUTPUTS += 6


INITIAL_TRAINING_RATE = 1e-4
BATCH_SIZE = 32
IMAGE_SIZE = 224 #Need to update image generation to set image size according to this parameter
REGENERATE_TRAINING_DATA = False
MAX_BATCHES_BEFORE_REPORTING = int(10000/BATCH_SIZE)
EXAMPLES_PER_EPOC = 3000000 #Run through it twice since there are only 3,000,000 examples right now
NUMBER_OF_REPORT_CYCLES = int(EXAMPLES_PER_EPOC/MAX_BATCHES_BEFORE_REPORTING) #Processing MAX_BATCHES_BEFORE_REPORTING per cycle
NUMBER_OF_DATA_GENERATION_CYCLES = 1 #Overriden if REGENERATE_TRAINING_DATA false
MIN_OBJECT_CENTER_DISTANCE = 1.0
MAX_OBJECT_CENTER_DISTANCE = 5.0
