TRANSLATION_TRACKING_ENABLED = True
ROTATION_TRACKING_ENABLED = True

NUMBER_OF_NETWORK_OUTPUTS = 0

if TRANSLATION_TRACKING_ENABLED : 
    NUMBER_OF_NETWORK_OUTPUTS += 3

if ROTATION_TRACKING_ENABLED :
    NUMBER_OF_NETWORK_OUTPUTS += 6


