TRANSLATION_TRACKING_ENABLED = True
ROTATION_TRACKING_ENABLED = True

NUMBER_OF_NETWORK_OUTPUTS = 0

if TRANSLATION_TRACKING_ENABLED : 
    NUMBER_OF_NETWORK_OUTPUTS += 3

if ROTATION_TRACKING_ENABLED :
    NUMBER_OF_NETWORK_OUTPUTS += 6


INITIAL_TRAINING_RATE = 2e-4
BATCH_SIZE = 64
IMAGE_SIZE = 224 #Need to update image generation to set image size according to this parameter
REGENERATE_TRAINING_DATA = False
MAX_BATCHES_BEFORE_REPORTING = int(10000/BATCH_SIZE)
EXAMPLES_PER_EPOC = 2000000
